version: "3.9"
services:
    mysql:
        image: mariadb:10.8.3
        # mariadb uses mysql_native_password as default authentication plugin but unix_socket is used for root user
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
        ports:
            - 3306:3306
    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
